# pnpm workspace configuration
# Add new patterns here when apps have nested directory structures
packages:
  - 'packages/*'
  - 'apps/*'
  # Nested app directories (monorepos within apps/)
  - 'apps/FamilyFun/frontend'
  - 'apps/BookingSystem/packages/*'
  - 'apps/elearning/*'
