import { Property } from '../types';

export const mockProperties: Property[] = [
  {
    id: 'prop-001',
    hostId: 'user-003',
    titleEn: 'Luxury Villa with Private Pool in Al Olaya',
    titleAr: 'فيلا فاخرة مع مسبح خاص في العليا',
    descriptionEn: 'Experience luxury living in this stunning 4-bedroom villa located in the prestigious Al Olaya district of Riyadh. Features include a private pool, modern furnishings, and a spacious garden perfect for family gatherings.',
    descriptionAr: 'استمتع بالحياة الفاخرة في هذه الفيلا الرائعة المكونة من 4 غرف نوم في حي العليا الراقي بالرياض. تشمل المميزات مسبحاً خاصاً وأثاثاً عصرياً وحديقة واسعة مثالية للتجمعات العائلية.',
    propertyType: 'villa',
    listingType: 'entire_place',
    location: {
      country: 'SA',
      city: 'Riyadh',
      neighborhood: 'Al Olaya',
      streetAddress: '123 King Fahd Road',
      buildingNumber: '15',
      latitude: 24.7136,
      longitude: 46.6753,
      directionsEn: 'Located near Kingdom Centre. Take the first right after the main entrance.',
      directionsAr: 'يقع بالقرب من برج المملكة. خذ أول يمين بعد المدخل الرئيسي.',
    },
    bedrooms: 4,
    bedroomDetails: [
      { id: 'br1', nameEn: 'Master Bedroom', nameAr: 'غرفة النوم الرئيسية', beds: [{ type: 'king', count: 1 }] },
      { id: 'br2', nameEn: 'Bedroom 2', nameAr: 'غرفة النوم 2', beds: [{ type: 'queen', count: 1 }] },
      { id: 'br3', nameEn: 'Bedroom 3', nameAr: 'غرفة النوم 3', beds: [{ type: 'double', count: 2 }] },
      { id: 'br4', nameEn: 'Bedroom 4', nameAr: 'غرفة النوم 4', beds: [{ type: 'single', count: 2 }] },
    ],
    beds: 6,
    bathrooms: 3.5,
    maxGuests: 8,
    sizeSqm: 450,
    amenities: ['wifi', 'air_conditioning', 'pool', 'free_parking', 'kitchen', 'washer', 'dryer', 'tv', 'dedicated_workspace', 'bbq_grill', 'outdoor_dining', 'halal_kitchen', 'prayer_mat', 'qibla_direction', 'bidet', 'smoke_alarm', 'fire_extinguisher', 'first_aid_kit'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800', order: 1, captionEn: 'Villa Exterior', captionAr: 'الواجهة الخارجية' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', order: 2, captionEn: 'Living Room', captionAr: 'غرفة المعيشة' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', order: 3, captionEn: 'Master Bedroom', captionAr: 'غرفة النوم الرئيسية' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800', order: 4, captionEn: 'Pool Area', captionAr: 'منطقة المسبح' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', order: 5, captionEn: 'Kitchen', captionAr: 'المطبخ' },
    ],
    pricing: {
      currency: 'SAR',
      basePrice: 1500,
      weekendPrice: 1800,
      cleaningFee: 200,
      securityDeposit: 500,
      extraGuestFee: 100,
      extraGuestAfter: 4,
      weeklyDiscountPercent: 10,
      monthlyDiscountPercent: 20,
    },
    houseRules: {
      checkInTimeStart: '15:00',
      checkInTimeEnd: '22:00',
      checkOutTime: '11:00',
      selfCheckIn: true,
      selfCheckInType: 'smart_lock',
      smokingAllowed: false,
      petsAllowed: false,
      eventsAllowed: false,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
      maxGuests: 8,
      familyOnly: true,
      additionalRulesEn: 'Please remove shoes before entering. Respect quiet hours for neighbors.',
      additionalRulesAr: 'يرجى خلع الأحذية قبل الدخول. احترم ساعات الهدوء للجيران.',
    },
    availability: {
      minStay: 2,
      maxStay: 30,
      advanceNotice: 1,
      preparationTime: 1,
      availabilityWindow: 365,
    },
    instantBook: true,
    familyOnly: true,
    femaleOnly: false,
    cancellationPolicy: 'moderate',
    status: 'active',
    rating: 4.92,
    reviewCount: 127,
    viewCount: 2450,
    createdAt: '2024-06-15T10:00:00Z',
    updatedAt: '2026-01-10T08:30:00Z',
    publishedAt: '2024-06-20T14:00:00Z',
  },
  {
    id: 'prop-002',
    hostId: 'user-002',
    titleEn: 'Modern Apartment with Burj Khalifa View',
    titleAr: 'شقة عصرية مع إطلالة على برج خليفة',
    descriptionEn: 'Wake up to stunning views of the Burj Khalifa in this elegantly designed 2-bedroom apartment in Downtown Dubai. Walking distance to Dubai Mall and the famous fountains.',
    descriptionAr: 'استيقظ على إطلالات خلابة لبرج خليفة في هذه الشقة الأنيقة المكونة من غرفتي نوم في وسط دبي. على مسافة قريبة من دبي مول والنوافير الشهيرة.',
    propertyType: 'apartment',
    listingType: 'entire_place',
    location: {
      country: 'AE',
      city: 'Dubai',
      neighborhood: 'Downtown Dubai',
      streetAddress: 'Boulevard Plaza Tower 1',
      buildingNumber: 'Tower 1',
      floorNumber: 32,
      latitude: 25.1972,
      longitude: 55.2744,
      directionsEn: 'Enter from Sheikh Mohammed bin Rashid Boulevard. Building has valet parking.',
      directionsAr: 'ادخل من شارع الشيخ محمد بن راشد. يوجد خدمة صف السيارات.',
    },
    bedrooms: 2,
    bedroomDetails: [
      { id: 'br1', nameEn: 'Master Bedroom', nameAr: 'غرفة النوم الرئيسية', beds: [{ type: 'king', count: 1 }] },
      { id: 'br2', nameEn: 'Guest Bedroom', nameAr: 'غرفة الضيوف', beds: [{ type: 'queen', count: 1 }] },
    ],
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    sizeSqm: 120,
    amenities: ['wifi', 'air_conditioning', 'tv', 'kitchen', 'washer', 'dryer', 'gym', 'pool', 'dedicated_workspace', 'elevator', 'bidet', 'halal_kitchen', 'prayer_mat', 'qibla_direction', 'smoke_alarm', 'security_cameras'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', order: 1, captionEn: 'Living Area with View', captionAr: 'منطقة المعيشة مع الإطلالة' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', order: 2, captionEn: 'Master Bedroom', captionAr: 'غرفة النوم الرئيسية' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800', order: 3, captionEn: 'Modern Kitchen', captionAr: 'المطبخ العصري' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', order: 4, captionEn: 'Burj Khalifa View', captionAr: 'إطلالة برج خليفة' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', order: 5, captionEn: 'Building Pool', captionAr: 'مسبح المبنى' },
    ],
    pricing: {
      currency: 'AED',
      basePrice: 950,
      weekendPrice: 1200,
      cleaningFee: 150,
      extraGuestFee: 75,
      extraGuestAfter: 2,
      weeklyDiscountPercent: 15,
      monthlyDiscountPercent: 25,
    },
    houseRules: {
      checkInTimeStart: '14:00',
      checkInTimeEnd: '23:00',
      checkOutTime: '12:00',
      selfCheckIn: true,
      selfCheckInType: 'keypad',
      smokingAllowed: false,
      petsAllowed: false,
      eventsAllowed: false,
      maxGuests: 4,
      familyOnly: false,
      additionalRulesEn: 'Building has strict security. Please register guests at reception.',
      additionalRulesAr: 'أمن المبنى صارم. يرجى تسجيل الضيوف في الاستقبال.',
    },
    availability: {
      minStay: 1,
      maxStay: 60,
      advanceNotice: 1,
      preparationTime: 0,
      availabilityWindow: 365,
    },
    instantBook: true,
    familyOnly: false,
    femaleOnly: false,
    cancellationPolicy: 'flexible',
    status: 'active',
    rating: 4.88,
    reviewCount: 89,
    viewCount: 1890,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2026-01-09T11:15:00Z',
    publishedAt: '2024-03-15T09:00:00Z',
  },
  {
    id: 'prop-003',
    hostId: 'user-003',
    titleEn: 'Desert Camp Experience in AlUla',
    titleAr: 'تجربة مخيم صحراوي في العلا',
    descriptionEn: 'Experience the magic of AlUla in this luxury desert camp. Traditional Bedouin-style tents with modern amenities, stargazing opportunities, and authentic Arabian hospitality.',
    descriptionAr: 'عش سحر العلا في هذا المخيم الصحراوي الفاخر. خيام على الطراز البدوي التقليدي مع وسائل الراحة الحديثة وفرص مراقبة النجوم والضيافة العربية الأصيلة.',
    propertyType: 'desert_camp',
    listingType: 'entire_place',
    location: {
      country: 'SA',
      city: 'AlUla',
      neighborhood: 'Madain Saleh Area',
      streetAddress: 'Desert Road',
      latitude: 26.7864,
      longitude: 37.9183,
      directionsEn: 'We will provide detailed directions and arrange pickup from AlUla airport.',
      directionsAr: 'سنوفر توجيهات تفصيلية ونرتب النقل من مطار العلا.',
    },
    bedrooms: 2,
    bedroomDetails: [
      { id: 'br1', nameEn: 'Main Tent', nameAr: 'الخيمة الرئيسية', beds: [{ type: 'king', count: 1 }] },
      { id: 'br2', nameEn: 'Second Tent', nameAr: 'الخيمة الثانية', beds: [{ type: 'double', count: 2 }] },
    ],
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    sizeSqm: 80,
    amenities: ['wifi', 'air_conditioning', 'breakfast_included', 'free_parking', 'outdoor_dining', 'fire_pit', 'halal_kitchen', 'prayer_mat', 'qibla_direction', 'first_aid_kit'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800', order: 1, captionEn: 'Desert Camp', captionAr: 'المخيم الصحراوي' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800', order: 2, captionEn: 'Luxury Tent Interior', captionAr: 'داخل الخيمة الفاخرة' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800', order: 3, captionEn: 'Starry Night', captionAr: 'ليلة مليئة بالنجوم' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1498889444388-e67ea62c464b?w=800', order: 4, captionEn: 'Desert Sunset', captionAr: 'غروب الصحراء' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800', order: 5, captionEn: 'Fire Pit Area', captionAr: 'منطقة النار' },
    ],
    pricing: {
      currency: 'SAR',
      basePrice: 2500,
      weekendPrice: 3000,
      cleaningFee: 0,
      extraGuestFee: 200,
      extraGuestAfter: 2,
      weeklyDiscountPercent: 5,
    },
    houseRules: {
      checkInTimeStart: '16:00',
      checkInTimeEnd: '20:00',
      checkOutTime: '10:00',
      selfCheckIn: false,
      smokingAllowed: true,
      petsAllowed: false,
      eventsAllowed: false,
      maxGuests: 6,
      familyOnly: true,
      additionalRulesEn: 'This is an eco-friendly camp. Please respect the desert environment.',
      additionalRulesAr: 'هذا مخيم صديق للبيئة. يرجى احترام البيئة الصحراوية.',
    },
    availability: {
      minStay: 1,
      maxStay: 7,
      advanceNotice: 3,
      preparationTime: 1,
      availabilityWindow: 180,
    },
    instantBook: false,
    familyOnly: true,
    femaleOnly: false,
    cancellationPolicy: 'strict',
    status: 'active',
    rating: 4.96,
    reviewCount: 45,
    viewCount: 980,
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2026-01-08T14:20:00Z',
    publishedAt: '2024-09-10T12:00:00Z',
  },
  {
    id: 'prop-004',
    hostId: 'user-002',
    titleEn: 'Cozy Studio in JBR Beach',
    titleAr: 'استوديو مريح في شاطئ جي بي آر',
    descriptionEn: 'Perfect beach getaway! This cozy studio is steps away from JBR Beach with access to The Walk shopping and dining. Ideal for solo travelers or couples.',
    descriptionAr: 'إجازة شاطئية مثالية! هذا الاستوديو المريح على بعد خطوات من شاطئ جي بي آر مع إمكانية الوصول إلى التسوق وتناول الطعام في الممشى. مثالي للمسافرين منفردين أو الأزواج.',
    propertyType: 'studio',
    listingType: 'entire_place',
    location: {
      country: 'AE',
      city: 'Dubai',
      neighborhood: 'Jumeirah Beach Residence',
      streetAddress: 'Sadaf Tower',
      buildingNumber: 'Sadaf 4',
      floorNumber: 15,
      latitude: 25.0785,
      longitude: 55.1340,
    },
    bedrooms: 0,
    bedroomDetails: [],
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    sizeSqm: 45,
    amenities: ['wifi', 'air_conditioning', 'tv', 'kitchen', 'washer', 'gym', 'pool', 'elevator', 'bidet', 'prayer_mat', 'smoke_alarm'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', order: 1, captionEn: 'Studio Overview', captionAr: 'نظرة عامة على الاستوديو' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800', order: 2, captionEn: 'Bedroom Area', captionAr: 'منطقة النوم' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800', order: 3, captionEn: 'Beach View', captionAr: 'إطلالة الشاطئ' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800', order: 4, captionEn: 'Bathroom', captionAr: 'الحمام' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800', order: 5, captionEn: 'JBR Beach', captionAr: 'شاطئ جي بي آر' },
    ],
    pricing: {
      currency: 'AED',
      basePrice: 450,
      weekendPrice: 550,
      cleaningFee: 75,
      weeklyDiscountPercent: 20,
      monthlyDiscountPercent: 35,
    },
    houseRules: {
      checkInTimeStart: '15:00',
      checkInTimeEnd: '22:00',
      checkOutTime: '11:00',
      selfCheckIn: true,
      selfCheckInType: 'lockbox',
      smokingAllowed: false,
      petsAllowed: false,
      eventsAllowed: false,
      maxGuests: 2,
      familyOnly: false,
    },
    availability: {
      minStay: 1,
      maxStay: 90,
      advanceNotice: 0,
      preparationTime: 0,
      availabilityWindow: 365,
    },
    instantBook: true,
    familyOnly: false,
    femaleOnly: false,
    cancellationPolicy: 'flexible',
    status: 'active',
    rating: 4.75,
    reviewCount: 234,
    viewCount: 3200,
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2026-01-11T06:00:00Z',
    publishedAt: '2023-11-05T14:00:00Z',
  },
  {
    id: 'prop-005',
    hostId: 'user-003',
    titleEn: 'Traditional Jeddah House in Al-Balad',
    titleAr: 'بيت جداوي تقليدي في البلد',
    descriptionEn: 'Stay in a beautifully restored traditional Jeddah house in the historic Al-Balad district. Experience authentic Arabian architecture with modern comforts.',
    descriptionAr: 'أقم في بيت جداوي تقليدي مرمم بشكل جميل في حي البلد التاريخي. عش تجربة العمارة العربية الأصيلة مع وسائل الراحة الحديثة.',
    propertyType: 'traditional_house',
    listingType: 'entire_place',
    location: {
      country: 'SA',
      city: 'Jeddah',
      neighborhood: 'Al-Balad',
      streetAddress: 'Souq Al-Alawi',
      latitude: 21.4858,
      longitude: 39.1925,
    },
    bedrooms: 3,
    bedroomDetails: [
      { id: 'br1', nameEn: 'Master Suite', nameAr: 'الجناح الرئيسي', beds: [{ type: 'king', count: 1 }] },
      { id: 'br2', nameEn: 'Heritage Room', nameAr: 'غرفة التراث', beds: [{ type: 'queen', count: 1 }] },
      { id: 'br3', nameEn: 'Family Room', nameAr: 'غرفة العائلة', beds: [{ type: 'single', count: 3 }] },
    ],
    beds: 5,
    bathrooms: 2,
    maxGuests: 7,
    sizeSqm: 200,
    amenities: ['wifi', 'air_conditioning', 'tv', 'kitchen', 'halal_kitchen', 'prayer_mat', 'quran', 'qibla_direction', 'bidet', 'indoor_fireplace', 'smoke_alarm', 'first_aid_kit'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', order: 1, captionEn: 'Traditional Facade', captionAr: 'الواجهة التقليدية' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800', order: 2, captionEn: 'Central Courtyard', captionAr: 'الفناء المركزي' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', order: 3, captionEn: 'Master Suite', captionAr: 'الجناح الرئيسي' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800', order: 4, captionEn: 'Majlis Area', captionAr: 'المجلس' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800', order: 5, captionEn: 'Rooftop Terrace', captionAr: 'شرفة السطح' },
    ],
    pricing: {
      currency: 'SAR',
      basePrice: 1200,
      weekendPrice: 1400,
      cleaningFee: 150,
      securityDeposit: 300,
      extraGuestFee: 80,
      extraGuestAfter: 4,
      weeklyDiscountPercent: 10,
    },
    houseRules: {
      checkInTimeStart: '14:00',
      checkInTimeEnd: '21:00',
      checkOutTime: '12:00',
      selfCheckIn: false,
      smokingAllowed: false,
      petsAllowed: false,
      eventsAllowed: false,
      maxGuests: 7,
      familyOnly: true,
      additionalRulesEn: 'This is a heritage property. Please handle all items with care.',
      additionalRulesAr: 'هذا عقار تراثي. يرجى التعامل مع جميع الأغراض بعناية.',
    },
    availability: {
      minStay: 2,
      maxStay: 14,
      advanceNotice: 2,
      preparationTime: 1,
      availabilityWindow: 270,
    },
    instantBook: false,
    familyOnly: true,
    femaleOnly: false,
    cancellationPolicy: 'moderate',
    status: 'active',
    rating: 4.94,
    reviewCount: 67,
    viewCount: 1450,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2026-01-07T09:30:00Z',
    publishedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'prop-006',
    hostId: 'user-002',
    titleEn: 'Beachfront Chalet in Kuwait',
    titleAr: 'شاليه على الشاطئ في الكويت',
    descriptionEn: 'Escape to this beautiful beachfront chalet in Kuwait. Perfect for family vacations with direct beach access, BBQ area, and stunning sunset views.',
    descriptionAr: 'اهرب إلى هذا الشاليه الجميل على الشاطئ في الكويت. مثالي للعطلات العائلية مع وصول مباشر للشاطئ ومنطقة شواء وإطلالات غروب خلابة.',
    propertyType: 'chalet',
    listingType: 'entire_place',
    location: {
      country: 'KW',
      city: 'Kuwait City',
      neighborhood: 'Fahaheel',
      streetAddress: 'Beach Road',
      latitude: 29.0818,
      longitude: 48.1312,
    },
    bedrooms: 3,
    bedroomDetails: [
      { id: 'br1', nameEn: 'Master Bedroom', nameAr: 'غرفة النوم الرئيسية', beds: [{ type: 'king', count: 1 }] },
      { id: 'br2', nameEn: 'Twin Room', nameAr: 'غرفة التوأم', beds: [{ type: 'single', count: 2 }] },
      { id: 'br3', nameEn: 'Bunk Room', nameAr: 'غرفة الأسرّة المزدوجة', beds: [{ type: 'bunk_bed', count: 2 }] },
    ],
    beds: 6,
    bathrooms: 2,
    maxGuests: 8,
    sizeSqm: 180,
    amenities: ['wifi', 'air_conditioning', 'tv', 'kitchen', 'free_parking', 'bbq_grill', 'outdoor_dining', 'halal_kitchen', 'prayer_mat', 'qibla_direction', 'bidet', 'smoke_alarm'],
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800', order: 1, captionEn: 'Chalet Exterior', captionAr: 'الشاليه من الخارج' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', order: 2, captionEn: 'Beach View', captionAr: 'إطلالة الشاطئ' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', order: 3, captionEn: 'Living Area', captionAr: 'منطقة المعيشة' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', order: 4, captionEn: 'Master Bedroom', captionAr: 'غرفة النوم الرئيسية' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1533044309907-0fa3413da946?w=800', order: 5, captionEn: 'BBQ Area', captionAr: 'منطقة الشواء' },
    ],
    pricing: {
      currency: 'KWD',
      basePrice: 85,
      weekendPrice: 110,
      cleaningFee: 15,
      extraGuestFee: 10,
      extraGuestAfter: 4,
    },
    houseRules: {
      checkInTimeStart: '15:00',
      checkInTimeEnd: '22:00',
      checkOutTime: '11:00',
      selfCheckIn: true,
      selfCheckInType: 'lockbox',
      smokingAllowed: true,
      petsAllowed: false,
      eventsAllowed: true,
      maxGuests: 8,
      familyOnly: false,
      additionalRulesEn: 'Beach equipment available. Please clean BBQ grill after use.',
      additionalRulesAr: 'معدات الشاطئ متوفرة. يرجى تنظيف شواية الشواء بعد الاستخدام.',
    },
    availability: {
      minStay: 1,
      maxStay: 30,
      advanceNotice: 1,
      preparationTime: 1,
      availabilityWindow: 365,
    },
    instantBook: true,
    familyOnly: false,
    femaleOnly: false,
    cancellationPolicy: 'flexible',
    status: 'active',
    rating: 4.82,
    reviewCount: 156,
    viewCount: 2100,
    createdAt: '2024-05-15T10:00:00Z',
    updatedAt: '2026-01-10T15:00:00Z',
    publishedAt: '2024-05-20T10:00:00Z',
  },
];

export const getPropertyById = (id: string): Property | undefined => {
  return mockProperties.find((property) => property.id === id);
};

export const getPropertiesByHost = (hostId: string): Property[] => {
  return mockProperties.filter((property) => property.hostId === hostId);
};

export const searchProperties = (filters: {
  city?: string;
  minPrice?: number;
  maxPrice?: number;
  propertyType?: string;
  instantBook?: boolean;
  familyOnly?: boolean;
}): Property[] => {
  return mockProperties.filter((property) => {
    if (filters.city && property.location.city.toLowerCase() !== filters.city.toLowerCase()) return false;
    if (filters.minPrice && property.pricing.basePrice < filters.minPrice) return false;
    if (filters.maxPrice && property.pricing.basePrice > filters.maxPrice) return false;
    if (filters.propertyType && property.propertyType !== filters.propertyType) return false;
    if (filters.instantBook && !property.instantBook) return false;
    if (filters.familyOnly && !property.familyOnly) return false;
    return true;
  });
};
