import { User, Host, GuestProfile } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-001',
    email: 'ahmed@example.com',
    phone: '501234567',
    phoneCountryCode: '+966',
    firstNameEn: 'Ahmed',
    lastNameEn: 'Al-Rashid',
    firstNameAr: 'أحمد',
    lastNameAr: 'الراشد',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    dateOfBirth: '1990-05-15',
    nationality: 'SA',
    preferredLanguage: 'ar',
    preferredCurrency: 'SAR',
    idVerificationStatus: 'verified',
    idDocumentType: 'national_id',
    isHost: false,
    isGuest: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2026-01-10T08:30:00Z',
    lastLoginAt: '2026-01-10T08:30:00Z',
    status: 'active',
  },
  {
    id: 'user-002',
    email: 'fatima@example.com',
    phone: '551234567',
    phoneCountryCode: '+971',
    firstNameEn: 'Fatima',
    lastNameEn: 'Al-Maktoum',
    firstNameAr: 'فاطمة',
    lastNameAr: 'آل مكتوم',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    dateOfBirth: '1988-11-20',
    nationality: 'AE',
    preferredLanguage: 'en',
    preferredCurrency: 'AED',
    idVerificationStatus: 'verified',
    idDocumentType: 'passport',
    isHost: true,
    isGuest: true,
    createdAt: '2023-06-10T10:00:00Z',
    updatedAt: '2026-01-08T14:20:00Z',
    lastLoginAt: '2026-01-11T09:15:00Z',
    status: 'active',
  },
  {
    id: 'user-003',
    email: 'mohammed@example.com',
    phone: '551234568',
    phoneCountryCode: '+966',
    firstNameEn: 'Mohammed',
    lastNameEn: 'Al-Saud',
    firstNameAr: 'محمد',
    lastNameAr: 'آل سعود',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    dateOfBirth: '1985-03-10',
    nationality: 'SA',
    preferredLanguage: 'ar',
    preferredCurrency: 'SAR',
    idVerificationStatus: 'verified',
    idDocumentType: 'national_id',
    isHost: true,
    isGuest: false,
    createdAt: '2022-08-01T10:00:00Z',
    updatedAt: '2026-01-05T16:45:00Z',
    lastLoginAt: '2026-01-11T07:00:00Z',
    status: 'active',
  },
];

export const mockHosts: Host[] = [
  {
    ...mockUsers[1],
    isHost: true,
    aboutEn: 'I love hosting travelers from around the world! My properties are carefully maintained to ensure you have the best stay in Dubai.',
    aboutAr: 'أحب استضافة المسافرين من جميع أنحاء العالم! عقاراتي تُعتنى بعناية لضمان أفضل إقامة لك في دبي.',
    languagesSpoken: ['Arabic', 'English', 'French'],
    responseRate: 98,
    responseTime: 'within an hour',
    isSuperhost: true,
    hostingSince: '2023-06-10',
    totalReviews: 127,
    averageRating: 4.92,
    verificationBadges: ['identity', 'phone', 'email'],
    tourismLicenseNumber: 'DET-2024-12345',
    tourismLicenseVerified: true,
    bankAccount: {
      bankName: 'Emirates NBD',
      accountHolderName: 'Fatima Al-Maktoum',
      iban: 'AE070331234567890123456',
      currency: 'AED',
      isVerified: true,
    },
  },
  {
    ...mockUsers[2],
    isHost: true,
    aboutEn: 'Riyadh native with a passion for hospitality. I manage several premium properties across Saudi Arabia, each designed for comfort and luxury.',
    aboutAr: 'من مواليد الرياض وشغوف بالضيافة. أدير عدة عقارات فاخرة في أنحاء المملكة العربية السعودية، كل منها مصمم للراحة والفخامة.',
    languagesSpoken: ['Arabic', 'English'],
    responseRate: 95,
    responseTime: 'within a few hours',
    isSuperhost: true,
    hostingSince: '2022-08-01',
    totalReviews: 256,
    averageRating: 4.88,
    verificationBadges: ['identity', 'phone', 'email', 'government_id'],
    tourismLicenseNumber: 'REGA-2023-67890',
    tourismLicenseVerified: true,
    bankAccount: {
      bankName: 'Al Rajhi Bank',
      accountHolderName: 'Mohammed Al-Saud',
      iban: 'SA0380000000608010167519',
      currency: 'SAR',
      isVerified: true,
    },
  },
];

export const mockGuestProfiles: GuestProfile[] = [
  {
    user: mockUsers[0],
    totalTrips: 12,
    memberSince: '2024-01-15',
    reviewsReceived: 8,
    averageRating: 4.8,
  },
];

export const getHostById = (id: string): Host | undefined => {
  return mockHosts.find((host) => host.id === id);
};

export const getUserById = (id: string): User | undefined => {
  return mockUsers.find((user) => user.id === id);
};
